/*
  Examples:
    /^(acceso|appeso|arreso)$/
    /^a(cc|pp|rr)eso$/
    /^a(c{2}|p{2}|r{2})eso$/
    /^a(cceso|ppeso|rreso)$/
    /^(acc|app|arr)eso$/
*/

console.log('acceso')
console.log('appeso')
console.log('arreso')
console.log()
console.log()
console.log()
console.log()
console.log('acceso')
console.log('appeso')
console.log('arreso')
console.log()
console.log()
console.log()
console.log()
console.log('acceso')
console.log('appeso')
console.log('arreso')
console.log()
console.log()
console.log()
console.log()